### ISSUE TITLE
Suggestion: remove fake client config

### ISSUE THREAD

**Issue by Dantemss** [openstax/exchange-ruby#10]
The fake client config has no parallel for the real client and is forced by the code in the fake client initializer to match the global config. I suggest pulling those values from the global config.

**Comment by kevinburleigh75** [comment]
The reason it doesn't pull from the client-side config is to match the behavior of the client when misconfigured.  We do test error cases, don't we?  :)

**Comment by Dantemss** [comment]
Well currently if it's misconfigured it will just error out when the client is instantiated, instead of when the call to Exchange is made.

**Comment by Dantemss** [comment]
I suppose those usually happen at the same time though... hmmm maybe it's fine.

**Comment by Dantemss** [comment]
Maybe it could raise a connection refused error instead (or whatever the real client does)

**Comment by kevinburleigh75** [comment]
Regardless of what we do, we _do not_ want to expose the internal implementation's errors to the caller.

**Comment by Dantemss** [comment]
I just meant that the FakeClient should raise the same error as the RealClient, not necessarily a ConnectionRefused error instead of:

```rb
raise "invalid server url"
```

and

```rb
raise "invalid platform credentials"
```

**Comment by kevinburleigh75** [comment]
It raises those exceptions deep down inside, but they are wrapped at the top level to provide a uniform interface.  Just FYI.

**Comment by Dantemss** [comment]
Ah I see. If I cause these exceptions in the console they work fine, but from the app they look like RuntimeErrors. Maybe it's just Lev interfering. I'll close.
